# Generated by Django 2.2.2 on 2019-07-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0002_page_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
    ]
